Restrictions:
  APPLICATION:
  - {value: teamviewerMac}
  - {value: chrome}
  BOOKMARKS:
  - {value: www.facebook.com}
  - {value: www.provnow.com}
  - {value: 'https://www.tutorialspoint.com/'}
  - {value: 'https://www.javatpoint.com/'}
  - {value: 'http://www.tachetechnologies.com'}
  - {value: 'http://tachetechnologies.com/provAdmin/'}
  - {value: 'https://www.facebook.com/'}
  - {value: 'https://testconsole.provexam.com/#/pages/testconsole'}
  CONTROL: [null, null]
  PORT:
  - {value: USB}
  - {value: HDMI}
access_id: 1034
rule_id: '1'
rule_name: basic
status: success
test_url: http://www.tachetechnologies.com
