# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testFormMain.ui'
#
# Created: Tue May 22 15:08:26 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!
import os
back_d="iVBORw0KGgoAAAANSUhEUgAABkAAAAZACAYAAAAhDI6nAAAABHNCSVQICAgIfAhkiAAAAF96VFh0UmF3IHByb2ZpbGUgdHlwZSBBUFAxAAAImeNKT81LLcpMVigoyk/LzEnlUgADYxMuE0sTS6NEAwMDCwMIMDQwMDYEkkZAtjlUKNEABZiYm6UBoblZspkpiM8FAE+6FWgbLdiMAAAgAElEQVR4nOzb244c1RmG4VqrB+8wNo4B2QQJKRdgq7uGJoILwtfEHUFXgXIegQgbgdgFEQiSiZyDpGCAsd3zd1et2jzPBaz/O3+1qgoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOBAb7311mnpDQAAAMCyrEoPAADm7cGDB2+uVquXNpvNq23bflB6DwAAALAMAggA0JsHDx68mXP+U1VVVc75RAQBAAAAhiKAAAC9OBs/OiIIAAAAMBQBBAA4uvPiRyfnfFLX9StN03w49C4AAABgOQQQAOConhQ/OimlSyIIAAAA0CcBBAA4mn3iR0cEAQAAAPokgAAAR3GR+NFJKV06PT292zTNR33tAgAAAJZJAAEADhaJH52U0mURBAAAADg2AQQAOMgh8aOTUrq83W7v7HY7EQQAAAA4CgEEAAg7Rvw444oIAgAAAByLAAIAhBw5fnSu1HX9YtM0Hx/5XQAAAGBhBBAA4MJ6ih9VVVVVSumqCAIAAAAcSgABAC6kz/jRSSld3W63t3e73Sd93gEAAADmSwABAPY2RPw445oIAgAAAEQJIADAXgaOH51rdV0/3zTNpwPfBQAAACZOAAEAnqpQ/KiqqqpSStdFEAAAAOCiBBAA4IlKxo9OSun6ZrO50bbtZyV3AAAAANMhgAAAjzWG+NHJOT9X1/WzTdN8XnoLAAAAMH4CCABwrjHFj05K6YYIAgAAAOxDAAEA/mCM8aOTUrqx2Wyutm37RektAAAAwHgJIADAb4w5fnRyzjdFEAAAAOBJBBAA4BdTiB+dnPPN7Xb7zG63+7L0FgAAAGB8BBAAoKqqacWPM26JIAAAAMB5BBAAYKrxo3NrvV7ntm2/Kj0EAAAAGA8BBAAWbuLxo6qqqso53xZBAAAAgLMEEABYsDnEj07O+fZms3nUtu03pbcAAAAA5QkgALBQc4ofnZzzCyIIAAAAUFUCCAAs0hzjRyfn/MJ6vf5P27bflt4CAAAAlCOAAMDCzDl+dHLOL77++usP33333X+W3gIAAACUIYAAwIIsIX50Hj169NJ6vf6pbdvvSm8BAAAAhieAAMBCLCl+dHLOd0QQAAAAWCYBBAAWYInxo5NzvlPX9Q9N03xfegsAAAAwHAEEAGZuyfGjk1K6K4IAAADAsgggADBj4sevRBAAAABYFgEEAGZK/PijlNLd9Xr9fdu2/yq9BQAAAOiXAAIAMyR+PF7O+eX79+9/99577/1QegsAAADQHwEEAGZG/Hi61Wr1ZxEEAAAA5k0AAYAZET/2d3Jycme9Xn/btu2PpbcAAAAAxyeAAMBMiB8Xller1csiCAAAAMyTAAIAMyB+hOXVavXyvXv3vn7//ff/XXoMAAAAcDwCCABMnPhxsHxycnL33r1734ggAAAAMB8CCABMmPhxNKuTk5O7b7zxxlfvvPPOT6XHAAAAAIfLpQcAADHix9E98/Dhw7+WHgEAAAAchx8gADBB4kdvVq+99tpfdrvd30sPAQAAAA4jgADAxIgfvRNBAAAAYAYEEACYEPFjMKvNZvNq27YflB4CAAAAxAggADAR4sewcs4nIggAAABMlwACABMgfpQhggAAAMB0CSAAMHLiR1kiCAAAAEyTAAIAIyZ+jEPO+aSu61eapvmw9BYAAABgPwIIAIyU+DEuKaVLIggAAABMhwACACMkfoyTCAIAAADTIYAAwMiIH+OWUrp0enp6t2maj0pvAQAAAB5PAAGAERE/piGldFkEAQAAgHETQABgJMSPaUkpXd5ut3d2u50IAgAAACMkgADACIgfk3VFBAEAAIBxEkAAoDDxY/Ku1HX9YtM0H5ceAgAAAPxKAAGAgsSPeUgpXRVBAAAAYFwEEAAoRPyYl5TS1e12e3u3231SegsAAAAggABAEeLHbF0TQQAAAGAcBBAAGJj4MXvX6rp+vmmaT0sPAQAAgCUTQABgQOLHMqSUrosgAAAAUJYAAgADET+WJaV0fbPZ3Gjb9rPSWwAAAGCJBBAAGID4sUw55+fqun62aZrPS28BAACApRFAAKBn4seypZRuiCAAAAAwPAEEAHokflBV/4sgm83matu2X5TeAgAAAEshgABAT8QPzso53xRBAAAAYDgCCAD0QPzgPDnnm9vt9pndbvdl6S0AAAAwdwIIAByZ+MFT3BJBAAAAoH8CCAAckfjBnm6t1+vctu1XpYcAAADAXAkgAHAk4gcXkXO+LYIAAABAf3LpAQAwB+IHQT+WHgAAAABzlUoPAICpEz+I+Pnnn//29ttv/6P0DgAAAJgrAQQADiB+ECF+AAAAQP8EEAAIEj+IED8AAABgGAIIAASIH0SIHwAAADAcAQQALkj8IEL8AAAAgGEJIABwAeIHEeIHAAAADE8AAYA9iR9EiB8AAABQhgACAHsQP4gQPwAAAKAcAQQAnkL8IEL8AAAAgLIEEAB4AvGDCPEDAAAAyhNAAOAxxA8ixA8AAAAYBwEEAM4hfhAhfgAAAMB4CCAA8DviBxHiBwAAAIyLAAIAZ4gfRIgfAAAAMD4CCAD8n/hBhPgBAAAA4ySAAEAlfhAjfgAAAMB4CSAALJ74QYT4AQAAAOMmgACwaOIHEeIHAAAAjJ8AAsBiiR9EiB8AAAAwDQIIAIskfhAhfgAAAMB0CCAALI74QYT4AQAAANMigACwKOIHEeIHAAAATI8AAsBiiB9EiB8AAAAwTQIIAIsgfhAhfgAAAMB0CSAAzJ74QYT4AQAAANMmgAAwa+IHEeIHAAAATJ8AAsBsiR9EiB8AAAAwDwIIALMkfhAhfgAAAMB8CCAAzI74QYT4AQAAAPMigAAwK+IHEeIHAAAAzI8AAsBsiB9EiB8AAAAwTwIIALMgfhAhfgAAAMB8CSAATJ74QYT4AQAAAPMmgAAwaeIHEeIHAAAAzJ8AAsBkiR9EiB8AAACwDAIIAJMkfhAhfgAAAMByCCAATI74QYT4AQAAAMsigAAwKeIHEeIHAAAALI8AAsBkiB9EiB8AAACwTAIIAJMgfhAhfgAAAMByCSAAjJ74QYT4AQAAAMsmgAAwauIHEeIHAAAAIIAAMFriBxHiBwAAAFBVAggAIyV+ECF+AAAAAB0BBIDRET+IED8AAACAswQQAEZF/CBC/AAAAAB+TwABYDTEDyLEDwAAAOA8AggAoyB+ECF+AAAAAI8jgABQnPhBhPgBAAAAPIkAAkBR4gcR4gcAAADwNAIIAMWIH0SIHwAAAMA+BBAAihA/iBA/AAAAgH0JIAAMTvwgQvwAAAAALkIAAWBQ4gcR4gcAAABwUQIIAIMRP4gQPwAAAIAIAQSAQYgfRIgfAAAAQJQAAkDvxA8ixA8AAADgEAIIAL0SP4gQPwAAAIBDCSAA9Eb8IEL8AAAAAI5BAAGgF+IHEeIHAAAAcCwCCABHJ34QIX4AAAAAxySAAHBU4gcR4gcAAABwbAIIAEcjfhAhfgAAAAB9EEAAOArxgwjxAwAAAOiLAALAwcQPIsQPAAAAoE8CCAAHET+IED8AAACAvgkgAISJH0SIHwAAAMAQBBAAQsQPIsQPAAAAYCgCCAAXJn4QIX4AAAAAQxJAALgQ8YMI8QMAAAAYmgACwN7EDyLEDwAAAKAEAQSAvYgfRIgfAAAAQCkCCABPJX4QIX4AAAAAJQkgADyR+EGE+AEAAACUJoAA8FjiBxHiBwAAADAGAggA5xI/iBA/AAAAgLEQQAD4A/GDCPEDAAAAGBMBBIDfED+IED8AAACAsRFAAPiF+EGE+AEAAACMkQACQFVV4gcx4gcAAAAwVgIIAOIHIeIHAAAAMGYCCMDCiR9EiB8AAADA2AkgAAsmfhAhfgAAAABTIIAALJT4QYT4AQAAAEyFAAKwQOIHEeIHAAAAMCUCCMDCiB9EiB8AAADA1AggAAsifhAhfgAAAABTJIAALIT4QYT4AQAAAEyVAAKwAOIHEeLHf9m3m13JrvqMw1UdMUiGkSLlNhCZ5YLghk5X1bG5ikyiIBAgDMEYg0UIVogsxXEgVpyObAkJu0/tzsBtu9t9Pqre2nuvr+e5gLXe+U9/AAAAoGUCCEDnxA8S4gcAAADQOgEEoGPiBwnxAwAAAOiBAALQKfGDhPgBAAAA9EIAAeiQ+EFC/AAAAAB6IoAAdEb8ICF+AAAAAL0RQAA6In6QED8AAACAHgkgAJ0QP0iIHwAAAECvBBCADogfJMQPAAAAoGcCCEDjxA8S4gcAAADQOwEEoGHiBwnxAwAAABiBAALQKPGDhPgBAAAAjEIAAWiQ+EFC/AAAAABGIoAANEb8ICF+AAAAAKMRQAAaIn6QED8AAACAEQkgAI0QP0iIHwAAAMCoBBCABogfJMQPAAAAYGQCCEDlxA8S4gcAAAAwOgEEoGLiBwnxAwAAAEAAAaiW+EFC/AAAAAD4nAACUCHxg4T4AQAAAPAVAQSgMuIHCfEDAAAA4GUCCEBFxA8S4gcAAADAqwQQgEqIHyTEDwAAAIDbCSAAFRA/SIgfAAAAAHcTQAAKEz9IiB8AAAAA9xNAAAoSP0iIHwAAAAAPE0AAChE/SIgfAAAAAKcRQAAKED9IiB8AAAAApxNAAFYmfpAQPwAAAADOI4AArEj8ICF+AAAAAJxPAAFYifhBQvwAAAAAyAggACsQP0iIHwAAAAA5AQRgYeIHCfEDAAAA4DICCMCCxA8S4gcAAADA5QQQgIWIHyTEDwAAAIB5CCAACxA/SIgfAAAAAPMRQABmJn6QED8AAAAA5iWAAMxI/CAhfgAAAADMTwABmIn4QUL8AAAAAFiGAAIwA/GDhPgBAAAAsBwBBOBC4gcJ8QMAAABgWQIIwAXEDxLiBwAAAMDyBBCAkPhBQvwAAAAAWIcAAhAQP0iIHwAAAADrEUAAziR+kBA/AAAAANYlgACcQfwgIX4AAAAArE8AATiR+EFC/AAAAAAoQwABOIH4QUL8AAAAAChHAAF4gPhBQvwAAAAAKEsAAbiH+EFC/AAAAAAoTwABuIP4QUL8AAAAAKiDAAJwC/GDhPgBAAAAUA8BBOBrxA8S4gcAAABAXQQQgBeIHyTEDwAAAID6CCAAz4kfJMQPAAAAgDoJIAAb8YOM+AEAAABQLwEEGJ74QUL8AAAAAKibAAIMTfwgIX4AAAAA1E8AAYYlfpAQPwAAAADaIIAAQxI/SIgfAAAAAO0QQIDhiB8kxA8AAACAtgggwFDEDxLiBwAAAEB7BBBgGOIHCfEDAAAAoE0CCDAE8YOE+AEAAADQLgEE6J74QUL8AAAAAGibAAJ0TfwgIX4AAAAAtE8AAbolfpAQPwAAAAD6IIAAXRI/SIgfAAAAAP0QQIDuiB8kxA8AAACAvgggQFfEDxLiBwAAAEB/BBCgG+IHCfEDAAAAoE8CCNAF8YOE+AEAAADQLwEEaJ74QUL8AAAAAOibAAI0TfwgIX4AAAAA9E8AAZolfpAQPwAAAADGIIAATRI/SIgfAAAAAOMQQIDmiB8kxA8AAACAsQggQFPEDxLiBwAAAMB4BBCgGeIHCfEDAAAAYEwCCNAE8YOE+AEAAAAwLgEEqJ74QUL8AAAAABibAAJUTfwgIX4AAAAAIIAA1RI/SIgfAAAAAGw2AghQKfGDhPgBAAAAwBcEEKA64gcJ8QMAAACAFwkgQFXEDxLiBwAAAABfJ4AA1RA/SIgfAAAAANxGAAGqIH6QED8AAAAAuIsAAhQnfpAQPwAAAAC4jwACFCV+kBA/AAAAAHiIAAIUI36QED8AAAAAOIUAAhQhfpAQPwAAAAA4lQACrE78ICF+AAAAAHAOAQRYlfhBQvwAAAAA4FwCCLAa8YOE+AEAAABAQgABViF+kBA/AAAAAEgJIMDixA8S4gcAAAAAlxBAgEWJHyTEDwAAAAAuJYAAixE/SIgfAAAAAMxBAAEWIX6QED8AAAAAmIsAAsxO/CAhfgAAAAAwJwEEmJX4QUL8AAAAAGBuAggwG/GDhPgBAAAAwBIEEGAW4gcJ8QMAAACApQggwMXEDxLiBwAAAABLEkCAi4gfJMQPAAAAAJYmgAAx8YOE+AEAAADAGgQQICJ+kBA/AAAAAFiLAAKcTfwgIX4AAAAAsCYBBDiL+EFC/AAAAABgbQIIcDLxg4T4AQAAAEAJAghwEvGDhPgBAAAAQCkCCPAg8YOE+AEAAABASQIIcC/xg4T4AQAAAEBpAghwJ/GDhPgBAAAAQA0EEOBW4gcJ8QMAAACAWgggwCvEDxLiBwAAAAA1EUCAl4gfJMQPAAAAAGojgABfEj9IiB8AAAAA1EgAATabjfhBRvwAAAAAoFYCCCB+EBE/AAAAAKiZAAKDEz9IiB8AAAAA1E4AgYGJHyTEDwAAAABaIIDAoMQPEuIHAAAAAK0QQGBA4gcAALCWx48f/0PpDQDAmB6VHgCsS/wAAAAAAEYggMBAxA8AAAAAYBQCCAxC/AAAAAAARiKAwADEDwAAAABgNAIIdE78AAAAAABGJIBAx8QPAAAAAGBUAgh0SvwAAAAAAEYmgECHxA8AAAAAYHQCCHRG/AAAAAAAEECgK+IHAAAAAMDnBBDohPgBAAAAAPAVAQQ6IH4AAAAAALxMAIHGiR8AAAAAAK8SQKBh4gcAAAAAwO0EEGiU+AEAAAAAcDcBBBokfgAAAAAA3E8AgcaIHwAAAAAADxNAoCHiBwAAAADAaQQQaIT4AQAAAABwOgEEGiB+AAAAAACcRwCByokfAAAAAADnE0CgYuIHAAAAAEBGAIFKiR8AAAAAADkBBCokfgAAAAAAXEYAgcqIHwAAAAAAlxNAoCLiBwAAAADAPAQQqIT4AQAAAAAwHwEEKiB+AAAAAADMSwCBwsQPAAAAAID5CSBQkPgBAAAAALAMAQQKET8AAAAAAJYjgEAB4gcAAAAAwLIEEFiZ+AEAAAAAsDwBBFYkfgAAAAAArEMAgZWIHwAAAAAA6xFAYAXiBwAAAADAugQQWJj4AQAAAACwPgEEFiR+AAAAAACUIYDAQsQPAAAAAIByBBBYgPgBAAAAAFCWAAIzEz8AAAAAAMoTQGBG4gcAAAAAQB0EEJiJ+AEAAAAAUA8BBGYgfgAAAAAA1EUAgQuJHwAAAAAA9RFA4ALiBwAAAABAnQQQCIkfAJM/K2YAAB/SSURBVAAAAAD1EkAgIH4AAAAAANRNAIEziR8AAAAAAPUTQAAAAAAAgO4IIHCm/X7/xjRNT0rvAAAAAADgbgIIBEQQAAAAAIC6CSAQEkEAAAAAAOolgMAFRBAAAAAAgDoJIHAhEQQAAAAAoD4CCMxABAEAAAAAqIsAAjMRQQAAAAAA6iGAwIxEEAAAAACAOgggMDMRBAAAAACgPAEEFiCCAAAAAACUJYDAQkQQAAAAAIByBBBYkAgCAAAAAFCGAAILE0EAAAAAANYngMAKRBAAAAAAgHUJILASEQQAAAAAYD0CCKxIBAEAAAAAWIcAAisTQQAAAAAAlieAQAEiCAAAAADAsgQQKEQEAQAAAABYjgACBYkgAAAAAADLEECgMBEEAAAAAGB+AghUQAQBAAAAAJiXAAKVEEEAAAAAAOYjgEBFRBAAAAAAgHkIIFAZEQQAAAAA4HICCFRIBAEAAAAAuIwAApUSQQAAAAAAcgIIVEwEAQAAAADICCBQOREEAAAAAOB8Agg0QAQBAAAAADiPAAKNEEEAAAAAAE4ngEBDRBAAAAAAgNMIINAYEQQAAAAA4GECCDRIBAEAAAAAuJ8AAo0SQQAAAAAA7iaAQMNEEAAAAACA2wkg0DgRBAAAAADgVQIIdEAEAQAAAAB4mQACnRBBAAAAAAC+IoBAR0QQAAAAAIDPCSDQGREEAAAAAEAAgS6JIAAAAADA6AQQ6JQIAgAAAACMTACBjokgAAAAAMCoBBDonAgCAAAAAIxIAIEBiCAAAAAAwGgEEBiECAIAAAAAjEQAgYGIIAAAAADAKAQQGIwIAgAAAACMYFt6AFDGd77znb9/9OjRX5feQVtubm7eub6+fr/0DgAAAAB4yF+UHgCU8dZbb/3nt771rb/Zbrd/WXoL7Xj06NHffvOb3/zzL3/5y49LbwEAAACA+wggMDARhIQIAgAAAEALBBAYnAhCQgQBAAAAoHYCCCCCEBFBAAAAAKiZAAJsNhsRhIwIAgAAAECtBBDgSyIICREEAAAAgBoJIMBLRBASIggAAAAAtRFAgFeIICREEAAAAABqIoAAtxJBSIggAAAAANRCAAHuJIKQEEEAAAAAqIEAAtxLBCEhggAAAABQmgACPEgEISGCAAAAAFCSAAKcRAQhIYIAAAAAUIoAApxMBCEhggAAAABQggACnEUEISGCAAAAALA2AQQ4mwhCQgQBAAAAYE0CCBARQUiIIAAAAACsRQABYiIICREEAAAAgDUIIMBFRBASIggAAAAASxNAgIuJICREEAAAAACWJIAAsxBBSIggAAAAACxFAAFmI4KQEEEAAAAAWIIAAsxKBCEhggAAAAAwNwEEmJ0IQkIEAQAAAGBOAgiwCBGEhAgCAAAAwFwEEGAxIggJEQQAAACAOQggwKJEEBIiCAAAAACXEkCAxYkgJEQQAAAAAC4hgACrEEFIiCAAAAAApAQQYDUiCAkRBAAAAICEAAKsSgQhIYIAAAAAcC4BBFidCEJCBAEAAADgHAIIUIQIQkIEAQAAAOBUAghQjAhCQgQBAAAA4BQCCFCUCEJCBAEAAADgIQIIUJwIQkIEAQAAAOA+AghQBRGEhAgCAAAAwF0EEKAaIggJEQQAAACA2wggQFVEEBIiCAAAAABfJ4AA1RFBSIggAAAAALxIAAGqJIKQEEEAAAAA+IIAAlRLBCEhggAAAACw2QggQOVEEBIiCAAAAAACCFA9EYSECAIAAAAwNgEEaIIIQkIEAQAAABiXAAI0QwQhIYIAAAAAjEkAAZoigpAQQQAAAADGI4AAzRFBSIggAAAAAGMRQIAmiSAkRBAAAACAcQggQLNEEBIiCAAAAMAYBBCgaSIICREEAAAAoH8CCNA8EYSECAIAAADQNwEE6IIIQkIEAQAAAOiXAAJ0QwQhIYIAAAAA9EkAAboigpAQQQAAAAD6I4AA3RFBSIggAAAAAH0RQIAuiSAkRBAAAACAfgggQLdEEBIiCAAAAEAfBBCgayIICREEAAAAoH0CCNA9EYSECAIAAADQNgEEGIIIQkIEAQAAAGiXAAIMQwQhIYIAAAAAtEkAAYYigpAQQQAAAADaI4AAwxFBSIggAAAAAG0RQIAhiSAkRBAAAACAdgggwLBEEBIiCAAAAEAbBBBgaCIICREEAAAAoH4CCDA8EYSECAIAAABQNwEEYCOCkBFBAAAAAOolgAA8J4KQEEEAAAAA6iSAALxABCEhggAAAADURwAB+BoRhIQIAgAAAFAXAQTgFiIICREEAAAAoB4CCMAdRBASIggAAABAHQQQgHuIICREEAAAAIDyBBCAB4ggJEQQAAAAgLIEEIATiCAkRBAAAACAcgQQgBOJICREEAAAAIAyBBCAM4ggJEQQAAAAgPUJIABnEkFIiCAAAAAA6xJAAAIiCAkRBAAAAGA9AghASAQhIYIAAAAArEMAAbiACEJCBAEAAABYngACcCERhIQIAgAAALAsAQRgBiIICREEAAAAYDkCCMBMRBASIggAAADAMgQQgBmJICREEAAAAID5CSAAMxNBSIggAAAAAPMSQAAWIIKQEEEAAAAA5iOAACxEBCEhggAAAADMQwABWJAIQkIEAQAAALicAAKwMBGEhAgCAAAAcBkBBGAFIggJEQQAAAAgJ4AArEQEISGCAAAAAGQEEIAViSAkRBAAAACA8wkgACsTQUiIIAAAAADnEUAAChBBSIggAAAAAKcTQAAKEUFIiCAAAAAApxFAAAoSQUiIIAAAAAAPE0AAChNBSIggAAAAAPcTQAAqIIKQEEEAAAAA7iaAAFRCBCEhggAAAADcTgABqIgIQkIEAQAAAHiVAAJQGRGEhAgCAAAA8DIBBKBCIggJEQQAAADgKwIIQKVEEBIiCAAAAMDnBBCAiokgJEQQAAAAAAEEoHoiCAkRBAAAABidAALQABGEhAgCAAAAjEwAAWiECEJCBAEAAABGJYAANEQEISGCAAAAACMSQAAaI4KQEEEAAACA0QggAA0SQUiIIAAAAMBIBBCARokgJEQQAAAAYBQCCEDDRBASIggAAAAwAgEEoHEiCAkRBAAAAOidAALQARGEhAgCAAAA9EwAAeiECEJCBAEAAAB6JYAAdEQEISGCAAAAAD0SQAA6I4KQEEEAAACA3gggAB0SQUiIIAAAAEBPBBCATokgJEQQAAAAoBcCCEDHRBASIggAAADQAwEEoHMiCAkRBAAAAGidAAIwABGEhAgCAAAAtEwAARiECEJCBAEAAABaJYAADEQEISGCAAAAAC0SQAAGI4KQEEEAAACA1gggAAMSQUiIIAAAAEBLBBCAQYkgJEQQAAAAoBUCCMDARBASIggAAADQAgEEYHAiCAkRBAAAAKidAAKACEJEBAEAAABqJoAAsNlsRBAyIggAAABQKwEEgC+JICREEAAAAKBGAggALxFBSIggAAAAQG0EEABeIYKQEEEAAACAmgggANxKBCEhggAAAAC1EEAAuJMIQkIEAQAAAGoggABwLxGEhAgCAAAAlCaAAPAgEYSECAIAAACUJIAAcBIRhIQIAgAAAJQigABwMhGEhAgCAAAAlCCAAHAWEYSECAIAAACsTQAB4GwiCAkRBAAAAFiTAAJARAQhIYIAAAAAaxFAAIiJICREEAAAAGANAggAFxFBSIggAAAAwNIEEAAuJoKQEEEAAACAJQkgAMxCBCEhggAAAABLEUAAmI0IQkIEAQAAAJYggAAwKxGEhAgCAAAAzE0AAWB2IggJEQQAAACYkwACwCJEEBIiCAAAADAXAQSAxYggJEQQAAAAYA4CCACLEkFIiCAAAADApQQQABYngpAQQQAAAIBLCCAArEIEISGCAAAAACkBBIDViCAkRBAAAAAgIYAAsCoRhIQIAgAAAJxLAAFgdSIICREEAAAAOIcAAkARIggJEQQAAAA4lQACQDEiCAkRBAAAADiFAAJAUSIICREEAAAAeIgAAkBxIggJEQQAAAC4jwACQBVEEBIiCAAAAHAXAQSAaoggJEQQAAAA4DYCCABVEUFIiCAAAADA1wkgAFRHBCEhggAAAAAvEkAAqJIIQkIEAQAAAL4ggABQLRGEhAgCAAAAbDYCCACVE0FIiCAAAACAAAJA9UQQEiIIAAAAjE0AAaAJIggJEQQAAADGJYAA0AwRhIQIAgAAAGMSQABoighCQgQBAACA8QggADRHBCEhggAAAMBYBBAAmiSCkBBBAAAAYBwCCADNEkFIiCAAAAAwBgEEgKaJICREEAAAAOifAAJA80QQEiIIAAAA9E0AAaALIggJEQQAAAD6JYAA0A0RhIQIAgAAAH0SQADoighCQgQBAACA/gggAHRHBCEhggAAAEBfBBAAuiSCkBBBAAAAoB8CCADdEkFIiCAAAADQBwEEgK6JICREEAAAAGifAAJA90QQEiIIAAAAtE0AAWAIIggJEQQAAADaJYAAMAwRhIQIAgAAAG0SQAAYighCQgQBAACA9gggAAxHBCEhggAAAEBbBBAAhiSCkBBBAAAAoB0CCADDEkFIiCAAAADQBgEEgKGJICREEAAAAKifAALA8EQQEiIIAAAA1E0AAYCNCEJGBAEAAIB6CSAA8JwIQkIEAQAAgDoJIADwAhGEhAgCAAAA9RFAAOBrRBASIggAAADURQABgFuIICREEAAAAKiHAAIAdxBBSIggAAAAUAcBBADuIYKQEEEAAACgPAEEAB4ggpAQQQAAAKAsAQQATiCCkBBBAAAAoBwBBABOJIKQEEEAAACgDAEEAM4ggpAQQQAAAGB9AggAnEkEISGCAAAAwLoEEAAIiCAkRBAAAABYjwACACERhIQIAgAAAOsQQADgAiIICREEAAAAlieAAMCFRBASIggAAAAs61HpAQDQg/1+/8Y0TU9K76A5f1V6AAAAAPTKBQgAzMQlCOe4ubn5/fX19buldwAAAECvBBAAmJEIwim22+17+/3+d6V3AAAAQM8EEACYmQjCfbbb7XtXV1e/Lb0DAAAAeieAAMACRBBuczwe39/tdr8pvQMAAABGIIAAwEJEEF50PB7fPxwO75TeAQAAAKMQQABgQSIIm81mM03TB4fD4deldwAAAMBIBBAAWJgIMrZpmj7Y7/e/Kr0DAAAARiOAAMAKRJAxHY/HPx4Oh7dL7wAAAIARCSAAsBIRZCzTNH14OBx+UXoHAAAAjEoAAYAViSBjmKbpw/1+/2bpHQAAADAyAQQAViaC9G273X602+1+XnoHAAAAjE4AAYACRJA+bbfbj66urn5WegcAAAAggABAMSJIX6ZperLb7X5aegcAAADwOQEEAAoSQfowTdOT/X7/RukdAAAAwFcEEAAoTARp23a7/Xi32/2k9A4AAADgZQIIAFRABGnTdrv9+Orq6seldwAAAACvEkAAoBIiSFuePXv2yePHj8UPAAAAqJQAAgAVEUHa8OzZs092u92PSu8AAAAA7iaAAEBlRJC6TdP0p/1+/8PSOwAAAID7CSAAUCERpE7P48cPSu8AAAAAHiaAAEClRJC6iB8AAADQFgEEAComgtTheDz++XA4fL/0DgAAAOB0AggAVE4EKet5/Phe6R0AAADAeQQQAGiACFKG+AEAAADtEkAAoBEiyLrEDwAAAGibAAIADRFBVvN0v9//U+kRAAAAQE4AAYDGiCCLe/r48eN/LD0CAAAAuIwAAgANEkEWI34AAABAJx6VHgAAZPb7/RvTND0pvaMjT7/xjW/8c+kRAAAAwDxcgABAw1yCzObpp59++uZut/u/0kMAAACAeQggANA4EeQy2+32+Omnn/78u9/9rmsaAAAA6IgAAgAdEEEy2+32+PTp0zdff/31/y29BQAAAJiXAAIAnRBBzvNF/Li+vv6o9BYAAABgfgIIAHREBDndZ5999tZrr732P6V3AAAAAMsQQACgMyLIwz777LM3X3/99Q9L7wAAAACWI4AAQIdEkLvd3Ny89dprr/136R0AAADAsgQQAOiUCPKqaZrePhwOfyi9AwAAAFieAAIAHRNBvjJN09v7/f6/Su8AAAAA1iGAAEDnRBDxAwAAAEYkgADAAEaOIDc3N+8cDocPSu8AAAAA1iWAAMAgRowgNzc371xfX79fegcAAACwPgEEAAYyUgR59OjRv+x2u/8ovQMAAAAoQwABgMGMEEFubm7+dbfbvVd6BwAAAFCOAAIAA+o5ghyPx3evr6//vfQOAAAAoCwBBAAG1WMEOR6P7x4Oh9+X3gEAAACUJ4AAwMB6iiA3Nze/v76+/rfSOwAAAIA6CCAAMLgeIsjz+PFu6R0AAABAPQQQAKDpCLLdbt/b7/e/K70DAAAAqIsAAgBsNps2I8h2u33v6urqt6V3AAAAAPURQACAL7UUQY7H4/u73e43pXcAAAAAdRJAAICXtBBBjsfj+4fD4Z3SOwAAAIB6CSAAwCtqjiDTNH1wOBx+XXoHAAAAUDcBBAC4VY0RZJqmD/b7/a9K7wAAAADqJ4AAAHeqKYIcj8c/Hg6Ht0vvAAAAANoggAAA96ohgkzT9OHhcPhFqf8BAACA9gggAMCDSkaQaZo+3O/3b679LwAAANA2AQQAOEmJCLLdbj/a7XY/X+s/AAAAoB8CCABwsjUjyHa7/ejq6upnS/8DAAAA9EkAAQDOskYEmabpyW63++lS7wMAAAD9E0AAgLMtGUGmaXqy3+/fmPtdAAAAYCwCCAAQWSKCbLfbj3e73U/meg8AAAAYlwACAMTmjCDb7fbjq6urH8+xCwAAAEAAAQAuMkcEefbs2SePHz8WPwAAAIDZCCAAwMUuiSDPnj37ZLfb/WiJXQAAAMC4BBAAYBZJBJmm6U/7/f6HC84CAAAABiWAAACzOSeCPI8fP1hjFwAAADAeAQQAmNUpEUT8AAAAAJYmgAAAs7svghyPxz8fDofvl9gFAAAAjEMAAQAWcVsEeR4/vldyFwAAADAGAQQAWMyLEUT8AAAAAAAAuvLtb3/770pvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAID/bw8OSAAAAAAE/X/dj1ABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4CREoGR1mRVm9AAAAAElFTkSuQmCC"
from PySide import QtCore, QtGui
import base64
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        print("==================================CALLING UI MAINWINDOW")
        print("\n")
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1173, 558)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: #E6E6E6;")   

        # self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget = QtGui.QTabWidget(MainWindow)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QTabWidget  QTabBar::tab{\n"
            "background-color: rgb(141, 141, 141);\n"
            "border-width: 2px;\n"
            "border-color: #aa0000;\n"
            "min-width: 12em;\n"
            "padding: 4px;\n"
            "color: rgb(255, 255, 255);\n"
            "height: 30px"
            "}\n"
            "\n"
            "QTabWidget  QTabBar::tab:!selected{\n"
            "background-color: #E6E6E6;\n"
            "font: 15px \"Roboto\";\n"
            "color: #606060;\n"
            "border-right: 1px solid #D3D3D3;\n"
            "}\n"
            "\n"
            "QTabWidget  QTabBar::tab:selected{\n"
            "background-color: #EEEEEE;\n"
            "font: 16px \"Roboto\";\n"
            "color: #606060;\n"
            "border-right: 1px solid #D3D3D3;\n"
            "text-align: center"
            "}\n"
            "\n"
            "") 

        # self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        self.corner_widget = QtGui.QWidget()
        self.corner_widget.setStyleSheet("min-width: 350px;float: right!important; \n")
        # self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout = QtGui.QHBoxLayout(self.corner_widget)
        # self.horizontalLayout.setSpacing(0)
        # self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        # self.bookMarkCombo = QtGui.QComboBox(self.centralwidget)
        self.bookMarkCombo = QtGui.QComboBox()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bookMarkCombo.sizePolicy().hasHeightForWidth())
        # self.bookMarkCombo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.bookMarkCombo.setFont(font)
        self.bookMarkCombo.setStyleSheet("background-color: rgb(255, 255, 255);\n"
            "font: 8pt \"Roboto\";\n"
            "border-width: 1px;\n"
            # "margin-left: 600px!important;\n"
            "\n"
            "position: absolute;\n"
            # "left: 100px;\n"
            "float: right!important; \n"
            "max-width: 300px!important;\n"
            "min-width: 300px!important;\n"
            "padding: 1px;\n"
            "height: 22px!important;\n"
            "border-color: rgb(170, 0, 0);\n"
            "color: #606060;")
        self.bookMarkCombo.setEditable(True)
        #self.bookMarkCombo.setCurrentText("")
        self.bookMarkCombo.setFrame(True)
        self.bookMarkCombo.setObjectName("bookMarkCombo")

        self.status_txt1 = QtGui.QLabel()
        movie = QtGui.QMovie("loading.gif")
        self.status_txt1.setMovie(movie)
        movie.start()
        self.status_txt1.setLayout(QtGui.QHBoxLayout())
        self.status_txt1.setStyleSheet(
            "border:none;\n"
            "margin-right:0px;\n"
            "position: absolute;\n"
            # "left: 100px;\n"
            "max-width: 60px!important;\n"
            "min-width: 60px!important;\n"
            "padding: 0px;\n"
            "height: 60px!important;\n"
        )
        self.horizontalLayout.addWidget(self.status_txt1)
        

        width=20
        self.backbutton=QtGui.QPushButton("");
        rMyIcon = QtGui.QPixmap("back_d.png");
        #rMyIcon.loadFromData(base64.b64decode(back_d))
        rMyIcon.setMaximumWidtht=50
        self.backbutton.setIcon(QtGui.QIcon(rMyIcon))
        self.backbutton.setIconSize(QtCore.QSize(20,20))
        self.backbutton.setObjectName("backBtn")
        self.backbutton.setMaximumWidth(width)
        self.backbutton.setStyleSheet(
            # "margin-left: 600px!important;\n"
            "\n"
            "border:none;\n"
            "position: absolute;\n"
            
            # "left: 100px;\n"

            "float: right!important; \n"
            "max-width: 30px!important;\n"
            "min-width: 30px!important;\n"
            "padding: 1px;\n"
            "height: 28px!important;\n"
            "color: #606060;")
        

        self.horizontalLayout.addWidget(self.backbutton)


        self.fwbutton=QtGui.QPushButton("");
        self.fwbutton.isFlat=True
        rMyIcon = QtGui.QPixmap("forward_d.png");
        self.fwbutton.setIcon(QtGui.QIcon(rMyIcon))
        self.fwbutton.setIconSize(QtCore.QSize(20,20))
        self.fwbutton.setObjectName("fwBtn")
        self.fwbutton.setMaximumWidth(width)
        self.fwbutton.setStyleSheet(
            # "margin-left: 600px!important;\n"
            "\n"
            "border:none;\n"
            "margin-right:15px;\n"
            "position: absolute;\n"
            # "left: 100px;\n"
            "float: right!important; \n"
            "max-width: 20px!important;\n"
            "min-width: 20px!important;\n"
            "padding: 1px;\n"
            "height: 22px!important;\n"
            )
        self.horizontalLayout.addWidget(self.fwbutton)
        
        
        self.horizontalLayout.addWidget( self.bookMarkCombo)
        # self.label_provImage = QtGui.QLabel(self.centralwidget)
        self.label_provImage = QtGui.QLabel(self.centralwidget)
        self.label_provImage.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_provImage.sizePolicy().hasHeightForWidth())
        self.label_provImage.setSizePolicy(sizePolicy)
        #self.label_provImage.setMinimumSize(QtCore.QSize(100, 2000))
        self.label_provImage.setMaximumSize(QtCore.QSize(150, 3500))
        font = QtGui.QFont()
        self.label_provImage.setFont(font)
        self.label_provImage.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_provImage.setStyleSheet("")
        self.label_provImage.setText("")
        #self.label_provImage.setPixmap(QtGui.QPixmap("icons/ProvLogoMain.png"))
        self.label_provImage.show()
        self.label_provImage.setAlignment(QtCore.Qt.AlignCenter)
        self.label_provImage.setWordWrap(True)
        self.label_provImage.setObjectName("label_provImage")
        self.label_provImage.setScaledContents(True)
        # self.horizontalLayout.addWidget(self.label_provImage)
        # self.Quit = QtGui.QPushButton(self.centralwidget)
        # self.Quit = QtGui.QPushButton(self.centralwidget)
        # self.Quit = QtGui.QToolButton(self.centralwidget)
        # sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.Quit.sizePolicy().hasHeightForWidth())
        # self.Quit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        # self.Quit.setFont(font)
        # self.Quit.setStyleSheet("QToolButton#Pressed{\n"
        #     "background: transparent;\n"
        #     "padding: 2px 2px!important;\n"
        #     "max-width: 10px!important;\n"
        #     "text-align: center;\n"
        #     "display: inline-block;\n"
        #     "}\n"
        #     "QToolButton#Quit:pressed {\n"
        #     "    border-style: inset;\n"
        #     "}\n"
        #     "\n"
        #     "")
        # self.Quit.setObjectName("Quit")
        # self.horizontalLayout.addWidget(self.Quit)

        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 1)
        # self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setObjectName("tabWidget")
        self.test_console = QtGui.QWidget()
        self.test_console.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.test_console.setObjectName("test_console")
        self.tabWidget.addTab(self.test_console, "")

        self.search_option = QtGui.QWidget()
        self.search_option.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.search_option.setObjectName("search_option")

        # self.tabWidget.setCornerWidget(self.Quit)
        self.formLayout = QtGui.QFormLayout(self.search_option)
        self.formLayout.setObjectName("formLayout")
        self.lineEdit = QtGui.QLineEdit()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(False)
        self.lineEdit.setFont(font)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        #self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.lineEdit)
        self.tabWidget.addTab(self.search_option, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        # MainWindow.setCentralWidget(self.centralwidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1173, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        button_icon = QtGui.QPixmap(self.get_push_button_path())
        # self.Quit.setIcon(button_icon)

        self.retranslateUi(MainWindow)
        self.bookMarkCombo.setCurrentIndex(-1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.tabWidget, QtCore.SIGNAL("currentChanged(int)"), self.tabWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.tabWidget.setCornerWidget(self.corner_widget)
        # self.tabWidget.setCornerWidget(self.bookMarkCombo)
        # self.tabWidget.setCornerWidget(self.Quit)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        # self.Quit.setText(QtGui.QApplication.translate("MainWindow", "", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.test_console), QtGui.QApplication.translate("MainWindow", "Test Console", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setText(QtGui.QApplication.translate("MainWindow", "Look Here For Help", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.search_option), QtGui.QApplication.translate("MainWindow", "Search Option", None, QtGui.QApplication.UnicodeUTF8))
    
    def get_push_button_path(self):
        return "{}{}img{}cross.png".format(os.getcwd(),os.sep, os.sep)
